# Generated by Django 3.0.8 on 2020-07-23 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0002_auto_20200721_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('positive', models.IntegerField(null=True)),
                ('total_tests', models.IntegerField(null=True)),
                ('deaths', models.IntegerField(null=True)),
                ('on_ventilator', models.IntegerField(null=True)),
                ('in_hospital', models.IntegerField(null=True)),
                ('in_icu', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='location',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locationdaydata',
            name='location_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='covidtracker.Location'),
        ),
    ]
