# Generated by Django 3.0.8 on 2020-07-24 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0005_auto_20200724_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('token', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationGroupLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='covidtracker.Location')),
                ('location_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='covidtracker.LocationGroup')),
            ],
        ),
    ]
