# Generated by Django 3.0.8 on 2020-07-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track19', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('token', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
