# Generated by Django 3.0.8 on 2020-07-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track19', '0004_auto_20200723_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationdaydata',
            old_name='location_token',
            new_name='location',
        ),
        migrations.AlterUniqueTogether(
            name='locationdaydata',
            unique_together={('location', 'date')},
        ),
    ]
