# Generated by Django 3.0.8 on 2020-08-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track19', '0007_auto_20200724_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidQuery',
            fields=[
                ('guid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('query', models.TextField(db_index=True, unique=True)),
            ],
        ),
    ]
