# Generated by Django 3.0.8 on 2020-08-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track19', '0008_guidquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollupLocationAttrRecentDelta',
            fields=[
                ('token', models.TextField(primary_key=True, serialize=False)),
                ('attr', models.TextField(db_index=True)),
                ('latest_date', models.DateField()),
                ('two_weeks_ago_date', models.DateField()),
                ('month_ago_date', models.DateField()),
                ('latest_value', models.FloatField(default=0)),
                ('two_weeks_ago_value', models.FloatField(default=0)),
                ('month_ago_value', models.FloatField(default=0)),
                ('two_week_delta', models.FloatField(default=0)),
                ('month_delta', models.FloatField(default=0)),
            ],
        ),
    ]
