# Generated by Django 3.0.8 on 2020-08-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track19', '0012_auto_20200815_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolluplocationattrrecentdelta',
            name='id',
        ),
        migrations.AddField(
            model_name='rolluplocationattrrecentdelta',
            name='k',
            field=models.TextField(default='0', primary_key=True, serialize=False),
        ),
    ]
