# Generated by Django 3.0.8 on 2020-08-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track19', '0013_auto_20200815_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolluplocationattrrecentdelta',
            name='peak_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rolluplocationattrrecentdelta',
            name='peak_value',
            field=models.FloatField(default=0),
        ),
    ]
