# Generated by Django 3.0.8 on 2020-10-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track19', '0014_auto_20200815_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
