# Generated by Django 3.0.8 on 2020-10-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track19', '0016_auto_20201002_2044'),
    ]

    operations = [
    ]
